### PR TITLE
fix(components/molecule/dataCounter): make buttons squared

### LINKED ISSUE #1738: Data counters - The buttons should be squared
**Describe the bug**
The buttons are not always 1:1 ratio

data counter width wrong

**Steps to reproduce**
1. Go to ['data counter'](https://sui-components.vercel.app/workbench/molecule/dataCounter/demo)
2. Scroll down to custom icons 
3. See error

**Expected behaviour**
The buttons should be squared

data counter width correct

### PR DESCRIPTION
**Pull request by mslourens**
ISSUES CLOSED: #1738

## molecule/dataCounter
**TASK**: #1738

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
Make input buttons square

### Screenshots - Animations
image

### CODE REVIEW

**Comment by andresin87** [comment]
I made some changes on the flow live editing in chrome in your branch. Can you plz conform it is working? @mslourens

**Comment by mslourens** [comment]
> I made some changes on the flow live editing in chrome in your branch. Can you plz conform it is working? @mslourens

I noticed that the labels inside the buttons were not center aligned anymore, so I fixed that as well.

**Comment by andresin87** [comment]
> > I made some changes on the flow live editing in chrome in your branch. Can you plz conform it is working? @mslourens
> 
> I noticed that the labels inside the buttons were not center aligned anymore, so I fixed that as well.

Can u center (v&h) it using css flexbox technique?

**Comment by mslourens** [comment]
Isn't `text-align: center` enough to center the label, like it is now? The padding for such a small button was not correct, so I set it to 0, which works quite well, I think.

**Comment by andresin87** [comment]
maybe now?

**Comment by delalama** [comment]
The simplest way i've found is to stop the padding propagation we are receiving.

Once deployed:
-Go to .sui-atomButton{
-You'll find a padding: 0 16 px  

Once deleted this padding the problem is solved.

**Comment by turolopezsanabria** [comment]
Oh, there's already a class to remove the paddings in the component button, check line 448 in [/atom/button/src/index.scss](https://github.com/SUI-Components/sui-components/blob/master/components/atom/button/src/index.scss#L448)

So... could you check if the change to fix the issue could be done in the [index.js](https://github.com/SUI-Components/sui-components/blob/master/components/molecule/dataCounter/src/index.js) file only?

**Comment by andresin87** [comment]
> Oh, there's already a class to remove the paddings in the component button, check line 448 in [/atom/button/src/index.scss](https://github.com/SUI-Components/sui-components/blob/master/components/atom/button/src/index.scss?rgh-link-date=2021-10-15T16%3A14%3A45Z#L448)
> 
> So... could you check if the change to fix the issue could be done in the [index.js](https://github.com/SUI-Components/sui-components/blob/master/components/molecule/dataCounter/src/index.js?rgh-link-date=2021-10-15T16%3A14%3A45Z) file only?

This class is added only when the children is empty. Not prop controlled.

**Review by andresin87 — APPROVED** [review]

**Pull request merged**
